### ISSUE TITLE
TODO: improve normalization + masking

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/hyperseti#15]
* [x] Compute spectral kurtosis and use to flag bad values
* [x] Implement mask for dedoppler kernel
* [x] Bandpass correction (particularly for coarse channel edges)
* [x] compute stats in inner region only (exclude band edges)
